### ISSUE TITLE
Update the Delete page - Code Area is Empty

### ISSUE THREAD

**Issue by MarcoMue** [dotnet/AspNetCore.Docs.de-de#90] opened 2021-03-31 15:12 UTC
> In this section, a custom error message is implemented when the call to SaveChanges fails.
> 
> Replace the code in Pages/Students/Delete.cshtml.cs with the following code. The changes are highlighted:

The specified Area is empty.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 8f592059-3328-88a8-5c6c-43121ac8a0a5
* Version Independent ID: f8a63abf-824b-5b80-e03d-abcb2c162b95
* Content: [Teil 2: Razor Pages mit EF Core in ASP.NET Core – CRUD](https://docs.microsoft.com/de-de/aspnet/core/data/ef-rp/crud?view=aspnetcore-5.0)
* Content Source: [aspnetcore/data/ef-rp/crud.md](https://github.com/dotnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/data/ef-rp/crud.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-data**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment] 2021-03-31 20:04
![image](https://user-images.githubusercontent.com/3605364/113203873-45994b80-9208-11eb-8eb5-c4fa5e8afe28.png)

I just updated the entire series yesterday. It will take another day for the changes to be translated. If this is not fixed  by April 2, 2021, reopen the issue or mention @Rick-Anderson

**Comment by MarcoMue** [comment] 2021-04-06 13:06
@Rick-Anderson The english version is fine, but the german version is still empty.

**Comment by Rick-Anderson** [comment] 2021-04-06 21:45
[Aktualisieren der Seite „Delete“ (Löschen)](https://docs.microsoft.com/de-de/aspnet/core/data/ef-rp/crud?view=aspnetcore-5.0#update-the-delete-page) is still empty.
English version [Update the Delete page](https://docs.microsoft.com/en-us/aspnet/core/data/ef-rp/crud?view=aspnetcore-5.0#update-the-delete-page)
@JasonCard  please help.

**Comment by JasonCard** [comment] 2021-04-06 22:25
@MarcoMue @Rick-Anderson We're sorry for the inconvenience caused by this delay. We are on a weekly cadence and this update should have been handed off for translation on 3/31, but our loc platform were experiencing issues last week and it didn't happen. The issue has been resolved, so it should be handed off tomorrow 4/7 and updated translation should be published by next week 4/13. Will update when completed.

**Comment by JasonCard** [comment] 2021-04-13 19:10
@MarcoMue @Rick-Anderson We're sorry again for the delay, but our loc platform were experiencing heavy workload again last week, so this article was finally handed off on 4/9, so updated ETA is 4/15.

**Comment by JasonCard** [comment] 2021-04-16 17:29
@MarcoMue Finally, this issue is now fixed :)
cc @Rick-Anderson

**Closed by JasonCard** 2021-04-16 17:29 UTC
